development:
  cloud_name: "dztjphpgl"
  api_key: "397966395591281"
  api_secret: "L7D_4Iw7OpO_16z5rkklt_MrAUM"

production:
  cloud_name: "dztjphpgl"
  api_key: "397966395591281"
  api_secret: "L7D_4Iw7OpO_16z5rkklt_MrAUM"

test:
  cloud_name: "dztjphpgl"
  api_key: "397966395591281"
  api_secret: "L7D_4Iw7OpO_16z5rkklt_MrAUM"
